version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 9000
        restart: unless-stopped
        environment:
            ROLE: app
        volumes:
            - ./php.ini:/etc/php/8.1/cli/conf.d/php.ini
            - .:/var/www/html
        networks:
            - appnet

    webserver:
        image: nginx:1.21.6-alpine
        ports:
            - '${APP_PORT:-8001}:80'
        restart: unless-stopped
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        volumes:
            - ./default.conf.template:/etc/nginx/templates/default.conf.template
            - .:/var/www/html
        networks:
            - appnet
        depends_on:
            - app

networks:
    appnet:
        driver: bridge
