version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 9000
        restart: always
        environment:
            ROLE: app
        volumes:
            - ./php.ini:/etc/php/8.1/cli/conf.d/php.ini
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - appnet

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - appnet

    webserver:
        image: nginx:1.21.6-alpine
        ports:
            - '${APP_PORT:-8005}:80'
        restart: always
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        volumes:
            - ./default.conf.template:/etc/nginx/templates/default.conf.template
            - .:/var/www/html
        networks:
            - appnet
        depends_on:
            - app

networks:
    appnet:
        driver: bridge

volumes:
    mysql-data:
        driver: local
